services:
  php:
    build: .
    container_name: shopmate-php
    volumes:
      - ./app:/var/www/html

  web:
    image: nginx:alpine
    container_name: shopmate-web
    depends_on:
      - php
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    container_name: shopmate-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: shopmate-phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   # must match the db root password
      PMA_ABSOLUTE_URI: http://127.0.0.1:8081/
      PMA_FORCE_SSL: 0 # allow use on http
    ports:
      - "8081:80"

volumes:
  db_data: {}   # <--- define the volume here